### ISSUE TITLE
Microses: null, so json is a subset of microses, and so microses can call more ses apis

### ISSUE THREAD

**Issue by erights** [erights/quasiParserGenerator#4]

**Comment by FUDCo** [comment]
Don't you mean "so JSON is a subset of microses?"

**Comment by erights** [comment]
yes. done

**Comment by erights** [comment]
The json case is compelling.

Resolution: add "null" back in.

**Comment by erights** [comment]
See also https://medium.com/@basarat/null-vs-undefined-in-typescript-land-dc0c7a5f240a#.sqq4cxnda
Despite including null, we should still generally recommend that microses users use undefined rather than null whenever they can make that choice.
